#!/usr/bin/env bash

# General
alias c='clear'
alias l='ls -al'
alias ..='cd ..'
alias ...='cd ../..'

# Use bat instead of cat.
if command -v bat &> /dev/null; then
  alias cat='bat --paging=never'
fi

# Alias fzf with preview to fzfp, so it doesn't mess with general-purpose fzf
# @see https://github.com/junegunn/fzf#preview-window
if command -v bat &> /dev/null && command -v fzf &> /dev/null; then
  alias fzfp="fzf --preview 'bat --color=always {}' --preview-window '~3'"
fi

# Git
alias ga='git add'
alias gbc='~/bin/git/create_branch.sh'
alias gbl='git branch --color'
alias gbp='~/bin/git/prune_branches.sh'
alias gbr='git branch --move'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gco='git checkout'
alias gs='git status -sb | sort -bf'
alias lg='lazygit'

# Neovim
alias vim=nvim
alias vi=nvim
alias v=nvim

# Tmux
alias tma='tmux attach-session -t '
alias tmk='tmux kill-session -t '
alias tml='tmux list-sessions'
alias tms='~/bin/tmux_quick_session.sh'
