#!/usr/bin/env bash

# General
alias c='clear'
alias l='ls -ahl'
alias ..='cd ..'
alias ...='cd ../..'

# If bat is installed, don't use paging
if command -v bat &> /dev/null; then
  alias bat='bat --paging=never'
fi

# Alias fzf with preview to fzfp, so it doesn't mess with general-purpose fzf
# @see https://github.com/junegunn/fzf#preview-window
if command -v bat &> /dev/null && command -v fzf &> /dev/null; then
  alias fzfp="fzf --preview 'bat --color=always {}' --preview-window '~3'"
fi

# Git: Branches
alias gbc='~/bin/git/create_branch.sh'
alias gbl='git branch --color'
alias gbr='git branch --move'
alias gbx='~/bin/git/prune_branches.sh'

# Git: Worktrees
alias gwc='~/bin/git/create_worktree.sh'
alias gwd='git worktree remove'
alias gwl='git worktree list'
alias gwp='~/bin/git/pull_worktree_branch.sh'

# Git: General
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log -10'
alias gco='git checkout'
alias gs='git status -sb | sort -bf'
alias lg='lazygit'

# Neovim
alias vim=nvim
alias vi=nvim
alias v=nvim

# Tmux
alias tma='tmux attach-session -t '
alias tmk='tmux kill-session -t '
alias tml='tmux list-sessions'
alias tms='~/bin/tmux_quick_session.sh'
