#!/usr/bin/env bash

# General
alias c='clear'
alias l='ls -ahl'
alias ..='cd ..'
alias ...='cd ../..'

# If bat is installed, don't use paging
if command -v bat &> /dev/null; then
  alias bat='bat --paging=never'
fi

# Alias fzf with preview to fzfp, so it doesn't mess with general-purpose fzf
# @see https://github.com/junegunn/fzf#preview-window
if command -v bat &> /dev/null && command -v fzf &> /dev/null; then
  alias fzfp="fzf --preview 'bat --color=always {}' --preview-window '~3'"
fi

# Git: Branches
alias gbc='git_branch_create.sh'
alias gbl='git branch --color'
alias gbr='git branch --move'
alias gbs='git_branch_switch.sh'
alias gbx='git_branch_prune.sh'

# Git: Worktrees
alias gwc='git_worktree_create.sh'
alias gwd='git worktree remove'
alias gwl='git worktree list'
alias gwp='git_worktree_pull.sh'

# Git: General
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log -10'
alias gs='git status -sb | sort -bf'
alias lg='lazygit'

# Neovim
alias vim=nvim
alias vi=nvim
alias v=nvim

# Tmux
alias tma='tmux_attach_session.sh'
alias tml='tmux list-sessions'
alias tms='tmux_start_session.sh'
alias tmx='tmux_kill_session.sh'
