#!/usr/bin/env bash

# User binaries
mkdir -p "$HOME/.local/bin"
export PATH="$HOME/.local/bin:$PATH"

# OpenCode is a special snowflake.
if test -d "$HOME/.opencode/bin"; then
  export PATH="$HOME/.opencode/bin:$PATH"
fi

# Global Mix Escripts
export PATH="$HOME/.mix/escripts:$PATH"

# Local Node.js package binaries
export PATH="./node_modules/.bin:$PATH"

# Go binaries
if command -v go &> /dev/null; then
  export PATH="$(go env GOPATH)/bin:$PATH"
fi

# Go executable
if test -d /usr/local/go/bin; then
  export PATH="$PATH:/usr/local/go/bin"
fi

# Load Mise, if it exists
if command -v mise &> /dev/null; then
  eval "$(mise activate zsh)"
fi
