#!sh

export SHELL=$(which zsh)

# Source environment variables.
source $XDG_CONFIG_HOME/zsh/variables

# Source paths. Must come before aliases.
source $XDG_CONFIG_HOME/zsh/paths

# Source aliases.
source $XDG_CONFIG_HOME/zsh/aliases

# Source keybindings.
source $XDG_CONFIG_HOME/zsh/bindings
