-- local function goto_file(file_index)
--   return function()
--     require('harpoon.ui').nav_file(file_index)
--   end
-- end
--
-- require('monooso.utils').register_keymap({ 'n' }, 'n', {
--   name = 'Harpoon',
--   e = { require('harpoon.mark').add_file, 'Harpoon file' },
--   n = { require('harpoon.ui').toggle_quick_menu, 'Toggle Harpoon' },
--
--   -- Navigate to the first four Harpooned files using the four right-hand home-row fingers.
--   t = { goto_file(1), 'First Harpooned file' },
--   s = { goto_file(2), 'Second Harpooned file' },
--   r = { goto_file(3), 'Third Harpooned file' },
--   a = { goto_file(4), 'Fourth Harpooned file' },
-- })
