-- require('monooso.utils').register_keymap({ 'n' }, 't', {
--   name = 'Testing',
--   t = { '<cmd>TestNearest<cr>', 'Run test' },
--   f = { '<cmd>TestFile<cr>', 'Run test file' },
--   s = { '<cmd>TestSuite<cr>', 'Run test suite' },
--   a = { '<cmd>TestLast<cr>', 'Re-run last test' },
--   j = { '<cmd>TestVisit<cr>', 'Go to last test' },
-- })
