#!sh

# Source environment variables
source $XDG_CONFIG_HOME/shell/variables

# Source aliases
source $XDG_CONFIG_HOME/shell/aliases

# Source paths
source $XDG_CONFIG_HOME/shell/paths

# Source keybindings
source $XDG_CONFIG_HOME/shell/bindings
