#!sh

# Source environment variables.
source $XDG_CONFIG_HOME/shell/variables

# Source paths. Must come before aliases.
source $XDG_CONFIG_HOME/shell/paths

# Source aliases.
source $XDG_CONFIG_HOME/shell/aliases

# Source keybindings.
source $XDG_CONFIG_HOME/shell/bindings
