# -----------------------------------------------------------------------------
# Basics
# -----------------------------------------------------------------------------
# Change prefix to C-Space
set -g prefix C-Space
unbind C-b

# Enable mouse support
set -g mouse on

# Appease Neovim :checkhealth
set -a terminal-features 'xterm-256color:RGB'
set -g focus-events on

# -----------------------------------------------------------------------------
# Window numbering
# -----------------------------------------------------------------------------
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# -----------------------------------------------------------------------------
# Appearance
# -----------------------------------------------------------------------------
set -g status-position bottom
set -g status-style 'bg=default,fg=white,dim'

setw -g window-status-style 'bg=default,fg=default'
setw -g window-status-current-style 'bg=default,fg=orange,bold'

# Simplify the status bar: nothing on the left, session name on the right
set -g status-left ""
set -g status-right "#S"

# -----------------------------------------------------------------------------
# Shortcuts
# -----------------------------------------------------------------------------
# Reload the tmux config using <Prefix>,
bind , source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded config"

# Toggle the status bar
bind s set status

# Quickly access LazyGit in an overlay
bind g display-popup -w 85% -h 85% -E lazygit
