# -----------------------------------------------------------------------------
# Basics
# -----------------------------------------------------------------------------
# Change prefix to C-t
set -g prefix C-t
unbind C-b

# Enable mouse support
set -g mouse on

# Appease Neovim :checkhealth
set -a terminal-features 'xterm-256color:RGB'
set -g focus-events on

# Use Vim keybindings.
set -g mode-keys vi

# -----------------------------------------------------------------------------
# Window numbering
# -----------------------------------------------------------------------------
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# -----------------------------------------------------------------------------
# Appearance
# -----------------------------------------------------------------------------
set -g status-position top

# -----------------------------------------------------------------------------
# Shortcuts
# -----------------------------------------------------------------------------
# Toggle the status bar
bind s set status

# Quickly access LazyGit in an overlay
bind g display-popup -w 95% -h 95% -E lazygit

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------
# Automatically install tpm and any plugins.
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Plugins to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'

# Configure Rosé Pine plugin
set -g @rose_pine_variant 'main'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_status_left_append_section ' '

# Initialse tpm
run '~/.tmux/plugins/tpm/tpm'
